#!/usr/bin/env python3
"""Bulk synthetic data generator — Part 11: DeFi protocols on Solana.
Target: ~100 records.
"""
import hashlib, json
from pathlib import Path

PROCESSED = Path(__file__).parent.parent / "data" / "processed"

def make_rec(content, category, lang="rust"):
    return {
        "id": hashlib.sha256(content.encode()).hexdigest(),
        "source": "synthetic/glan", "source_type": "synthetic",
        "content": content, "language": lang, "license": "synthetic-original",
        "metadata": {"method": "glan", "category": category, "anchor_version_class": "modern"},
    }

records = []

# ── 1. AMM / DEX (15) ──
AMM = [
    ("constant_product", "How do I implement a constant product AMM (x*y=k) in Anchor?",
     "```rust\nuse anchor_lang::prelude::*;\nuse anchor_spl::token::{self, Token, TokenAccount, Transfer};\n\n#[account]\n#[derive(InitSpace)]\npub struct Pool {\n    pub mint_a: Pubkey,\n    pub mint_b: Pubkey,\n    pub reserve_a: u64,\n    pub reserve_b: u64,\n    pub lp_mint: Pubkey,\n    pub fee_bps: u16,\n    pub authority: Pubkey,\n    pub bump: u8,\n}\n\npub fn swap(ctx: Context<Swap>, amount_in: u64, min_amount_out: u64) -> Result<()> {\n    let pool = &mut ctx.accounts.pool;\n    let fee = amount_in.checked_mul(pool.fee_bps as u64).unwrap() / 10_000;\n    let amount_in_after_fee = amount_in.checked_sub(fee).unwrap();\n    \n    // x * y = k\n    let new_reserve_a = pool.reserve_a.checked_add(amount_in_after_fee).unwrap();\n    let amount_out = pool.reserve_b\n        .checked_mul(amount_in_after_fee).unwrap()\n        .checked_div(new_reserve_a).unwrap();\n    \n    require!(amount_out >= min_amount_out, PoolError::SlippageExceeded);\n    \n    pool.reserve_a = new_reserve_a;\n    pool.reserve_b = pool.reserve_b.checked_sub(amount_out).unwrap();\n    \n    // CPI transfers...\n    Ok(())\n}\n```"),
    ("add_liquidity", "How do I implement adding liquidity to an AMM pool?",
     "```rust\npub fn add_liquidity(\n    ctx: Context<AddLiquidity>,\n    amount_a: u64,\n    amount_b: u64,\n    min_lp_tokens: u64,\n) -> Result<()> {\n    let pool = &mut ctx.accounts.pool;\n    \n    let lp_tokens = if pool.reserve_a == 0 {\n        // Initial liquidity: LP tokens = sqrt(amount_a * amount_b)\n        (amount_a as f64 * amount_b as f64).sqrt() as u64\n    } else {\n        // Proportional: LP tokens based on smaller ratio\n        let ratio_a = amount_a.checked_mul(pool.lp_supply).unwrap() / pool.reserve_a;\n        let ratio_b = amount_b.checked_mul(pool.lp_supply).unwrap() / pool.reserve_b;\n        ratio_a.min(ratio_b)\n    };\n    \n    require!(lp_tokens >= min_lp_tokens, PoolError::SlippageExceeded);\n    \n    pool.reserve_a = pool.reserve_a.checked_add(amount_a).unwrap();\n    pool.reserve_b = pool.reserve_b.checked_add(amount_b).unwrap();\n    \n    // Mint LP tokens to user\n    // CPI: token::mint_to with PDA signer\n    Ok(())\n}\n```"),
    ("remove_liquidity", "How do I implement removing liquidity?",
     "```rust\npub fn remove_liquidity(\n    ctx: Context<RemoveLiquidity>,\n    lp_amount: u64,\n    min_a: u64,\n    min_b: u64,\n) -> Result<()> {\n    let pool = &mut ctx.accounts.pool;\n    let share = lp_amount as u128 * 10_000 / pool.lp_supply as u128;\n    \n    let amount_a = (pool.reserve_a as u128 * share / 10_000) as u64;\n    let amount_b = (pool.reserve_b as u128 * share / 10_000) as u64;\n    \n    require!(amount_a >= min_a && amount_b >= min_b, PoolError::SlippageExceeded);\n    \n    pool.reserve_a -= amount_a;\n    pool.reserve_b -= amount_b;\n    \n    // Burn LP tokens, transfer A and B back to user\n    Ok(())\n}\n```"),
    ("price_from_reserves", "How do I calculate token price from AMM reserves?",
     "```rust\n// Price of A in terms of B\nlet price_a = pool.reserve_b as f64 / pool.reserve_a as f64;\n\n// In integer math (basis points precision):\nlet price_bps = pool.reserve_b\n    .checked_mul(10_000).unwrap()\n    .checked_div(pool.reserve_a).unwrap();\n\n// Price impact for a swap of `amount_in`:\nlet new_reserve_a = pool.reserve_a + amount_in;\nlet amount_out = pool.reserve_b * amount_in / new_reserve_a;\nlet effective_price = amount_in * 10_000 / amount_out;\nlet price_impact_bps = effective_price - price_bps;  // Higher = more impact\n```"),
    ("slippage", "How do I implement slippage protection?",
     "```rust\n// In the swap instruction:\nrequire!(\n    amount_out >= min_amount_out,\n    PoolError::SlippageExceeded\n);\n\n// Client-side: calculate with tolerance\nconst estimatedOutput = calculateSwapOutput(amountIn, reserveA, reserveB);\nconst minOutput = estimatedOutput * (1 - slippageTolerance); // e.g., 0.5%\n\nawait program.methods\n    .swap(new BN(amountIn), new BN(minOutput))\n    .accounts({...})\n    .rpc();\n```"),
]
for name, q, a in AMM:
    records.append(make_rec(f"### Question\n{q}\n\n### Answer\n{a}", "defi_amm"))

# ── 2. Lending (10) ──
LENDING = [
    ("deposit_collateral", "How do I implement collateral deposit for a lending protocol?",
     "```rust\n#[account]\n#[derive(InitSpace)]\npub struct UserPosition {\n    pub authority: Pubkey,\n    pub collateral_amount: u64,\n    pub borrowed_amount: u64,\n    pub collateral_mint: Pubkey,\n    pub last_update: i64,\n    pub bump: u8,\n}\n\npub fn deposit_collateral(ctx: Context<Deposit>, amount: u64) -> Result<()> {\n    let position = &mut ctx.accounts.user_position;\n    position.collateral_amount = position.collateral_amount.checked_add(amount)\n        .ok_or(LendingError::MathOverflow)?;\n    position.last_update = Clock::get()?.unix_timestamp;\n    \n    // Transfer collateral tokens from user to vault\n    token::transfer(\n        CpiContext::new(ctx.accounts.token_program.to_account_info(),\n            Transfer {\n                from: ctx.accounts.user_collateral.to_account_info(),\n                to: ctx.accounts.vault_collateral.to_account_info(),\n                authority: ctx.accounts.user.to_account_info(),\n            }),\n        amount,\n    )?;\n    Ok(())\n}\n```"),
    ("health_factor", "How do I calculate health factor for liquidation?",
     "```rust\n// Health factor = (collateral_value * ltv_ratio) / borrowed_value\n// If health_factor < 1.0, position is liquidatable\n\npub fn calculate_health_factor(\n    collateral_amount: u64,\n    collateral_price: u64,  // price in USD with 6 decimals\n    borrowed_amount: u64,\n    borrow_price: u64,\n    ltv_bps: u16,  // e.g., 7500 = 75%\n) -> Result<u64> {\n    let collateral_value = (collateral_amount as u128)\n        .checked_mul(collateral_price as u128).unwrap()\n        .checked_mul(ltv_bps as u128).unwrap()\n        .checked_div(10_000).unwrap();\n    \n    let borrowed_value = (borrowed_amount as u128)\n        .checked_mul(borrow_price as u128).unwrap();\n    \n    if borrowed_value == 0 {\n        return Ok(u64::MAX); // No borrows = infinite health\n    }\n    \n    // Return health in basis points (10000 = 1.0)\n    Ok((collateral_value * 10_000 / borrowed_value) as u64)\n}\n```"),
    ("interest_rate", "How do I implement interest rate calculation?",
     "```rust\n// Simple linear interest rate model:\n// rate = base_rate + utilization * slope\n\npub fn calculate_interest_rate(\n    total_deposits: u64,\n    total_borrows: u64,\n    base_rate_bps: u16,    // e.g., 200 = 2%\n    slope_bps: u16,        // e.g., 2000 = 20%\n    kink_utilization: u16, // e.g., 8000 = 80%\n    jump_slope_bps: u16,   // e.g., 10000 = 100%\n) -> u16 {\n    if total_deposits == 0 { return base_rate_bps; }\n    \n    let utilization = (total_borrows * 10_000 / total_deposits) as u16;\n    \n    if utilization <= kink_utilization {\n        base_rate_bps + utilization * slope_bps / 10_000\n    } else {\n        // Jump rate above kink\n        let normal_rate = base_rate_bps + kink_utilization * slope_bps / 10_000;\n        let excess = utilization - kink_utilization;\n        normal_rate + excess * jump_slope_bps / 10_000\n    }\n}\n```"),
    ("liquidation", "How do I implement liquidation in a lending protocol?",
     "```rust\npub fn liquidate(\n    ctx: Context<Liquidate>,\n    repay_amount: u64,\n) -> Result<()> {\n    let position = &ctx.accounts.borrower_position;\n    \n    // Check position is underwater\n    let health = calculate_health_factor(/* ... */)?;\n    require!(health < 10_000, LendingError::PositionHealthy);  // < 1.0\n    \n    // Liquidation bonus (e.g., 5%)\n    let bonus_bps: u64 = 500;\n    let collateral_to_seize = repay_amount\n        .checked_mul(10_000 + bonus_bps).unwrap()\n        .checked_div(10_000).unwrap();\n    \n    // Cap at max liquidation (e.g., 50% of position)\n    let max_repay = position.borrowed_amount / 2;\n    require!(repay_amount <= max_repay, LendingError::ExcessiveLiquidation);\n    \n    // Transfer repayment from liquidator\n    // Transfer collateral to liquidator (with bonus)\n    Ok(())\n}\n```"),
    ("flash_loan", "How do I implement a flash loan?",
     "```rust\npub fn flash_borrow(ctx: Context<FlashBorrow>, amount: u64) -> Result<()> {\n    // Verify repayment instruction exists later in the transaction\n    let ixs = &ctx.accounts.instruction_sysvar;\n    let current = instructions::load_current_index_checked(ixs)? as usize;\n    \n    let mut found_repay = false;\n    for i in (current + 1).. {\n        match instructions::load_instruction_at_checked(i, ixs) {\n            Ok(ix) => {\n                if ix.program_id == crate::ID {\n                    // Check it's a flash_repay instruction\n                    found_repay = true;\n                    break;\n                }\n            }\n            Err(_) => break,\n        }\n    }\n    require!(found_repay, LendingError::MissingRepayment);\n    \n    // Transfer tokens to borrower\n    let fee = amount * 9 / 10_000;  // 0.09% fee\n    // Record expected repayment: amount + fee\n    Ok(())\n}\n```"),
]
for name, q, a in LENDING:
    records.append(make_rec(f"### Question\n{q}\n\n### Answer\n{a}", "defi_lending"))

# ── 3. Staking (10) ──
STAKING = [
    ("reward_accumulator", "How do I implement per-share reward distribution?",
     "```rust\n#[account]\npub struct StakePool {\n    pub total_staked: u64,\n    pub reward_per_share: u128,  // Accumulated rewards per share (scaled by 1e12)\n    pub last_reward_time: i64,\n    pub reward_rate: u64,        // Tokens per second\n}\n\n#[account]\npub struct UserStake {\n    pub amount: u64,\n    pub reward_debt: u128,  // reward_per_share at time of last claim\n}\n\npub fn update_pool(pool: &mut StakePool) -> Result<()> {\n    let clock = Clock::get()?;\n    if pool.total_staked == 0 { \n        pool.last_reward_time = clock.unix_timestamp;\n        return Ok(());\n    }\n    let elapsed = (clock.unix_timestamp - pool.last_reward_time) as u64;\n    let rewards = elapsed * pool.reward_rate;\n    pool.reward_per_share += (rewards as u128 * 1_000_000_000_000) / pool.total_staked as u128;\n    pool.last_reward_time = clock.unix_timestamp;\n    Ok(())\n}\n\npub fn pending_rewards(pool: &StakePool, user: &UserStake) -> u64 {\n    let pending = (user.amount as u128 * pool.reward_per_share / 1_000_000_000_000)\n        .checked_sub(user.reward_debt).unwrap_or(0);\n    pending as u64\n}\n```"),
    ("stake", "How do I implement staking with cooldown?",
     "```rust\npub fn stake(ctx: Context<Stake>, amount: u64) -> Result<()> {\n    update_pool(&mut ctx.accounts.pool)?;\n    let user = &mut ctx.accounts.user_stake;\n    let pool = &ctx.accounts.pool;\n    \n    if user.amount > 0 {\n        let pending = pending_rewards(pool, user);\n        // Transfer pending rewards to user\n    }\n    \n    user.amount = user.amount.checked_add(amount).unwrap();\n    user.reward_debt = user.amount as u128 * pool.reward_per_share / 1_000_000_000_000;\n    \n    ctx.accounts.pool.total_staked += amount;\n    // Transfer tokens from user to pool vault\n    Ok(())\n}\n\npub fn unstake(ctx: Context<Unstake>, amount: u64) -> Result<()> {\n    let user = &mut ctx.accounts.user_stake;\n    require!(user.amount >= amount, StakeError::InsufficientStake);\n    \n    // Start cooldown\n    user.unstake_requested = amount;\n    user.cooldown_end = Clock::get()?.unix_timestamp + COOLDOWN_SECONDS;\n    Ok(())\n}\n\npub fn withdraw(ctx: Context<Withdraw>) -> Result<()> {\n    let user = &mut ctx.accounts.user_stake;\n    require!(Clock::get()?.unix_timestamp >= user.cooldown_end, StakeError::CooldownActive);\n    let amount = user.unstake_requested;\n    user.unstake_requested = 0;\n    user.amount -= amount;\n    // Transfer tokens back\n    Ok(())\n}\n```"),
]
for name, q, a in STAKING:
    records.append(make_rec(f"### Question\n{q}\n\n### Answer\n{a}", "defi_staking"))

# ── 4. Vesting (8) ──
VESTING = [
    ("linear_vesting", "How do I implement linear token vesting?",
     "```rust\n#[account]\n#[derive(InitSpace)]\npub struct VestingSchedule {\n    pub beneficiary: Pubkey,\n    pub mint: Pubkey,\n    pub total_amount: u64,\n    pub claimed_amount: u64,\n    pub start_time: i64,\n    pub end_time: i64,\n    pub cliff_time: i64,\n    pub bump: u8,\n}\n\npub fn claim(ctx: Context<Claim>) -> Result<()> {\n    let schedule = &mut ctx.accounts.vesting;\n    let clock = Clock::get()?;\n    \n    require!(clock.unix_timestamp >= schedule.cliff_time, VestError::CliffNotReached);\n    \n    let elapsed = (clock.unix_timestamp - schedule.start_time) as u64;\n    let duration = (schedule.end_time - schedule.start_time) as u64;\n    \n    let vested = if clock.unix_timestamp >= schedule.end_time {\n        schedule.total_amount\n    } else {\n        schedule.total_amount * elapsed / duration\n    };\n    \n    let claimable = vested.checked_sub(schedule.claimed_amount)\n        .ok_or(VestError::NothingToClaim)?;\n    require!(claimable > 0, VestError::NothingToClaim);\n    \n    schedule.claimed_amount += claimable;\n    // Transfer claimable tokens from vault PDA to beneficiary\n    Ok(())\n}\n```"),
    ("streaming", "How do I implement token streaming (Streamflow-style)?",
     "```rust\n// Token streaming = continuous vesting with per-second granularity\n// Claimable amount increases every second\n\npub fn claim_stream(ctx: Context<ClaimStream>) -> Result<()> {\n    let stream = &mut ctx.accounts.stream;\n    let now = Clock::get()?.unix_timestamp;\n    \n    let rate_per_second = stream.total_amount / (stream.end_time - stream.start_time) as u64;\n    let elapsed_since_last = (now - stream.last_claim_time) as u64;\n    let claimable = rate_per_second * elapsed_since_last;\n    \n    let actual = claimable.min(stream.total_amount - stream.claimed_amount);\n    stream.claimed_amount += actual;\n    stream.last_claim_time = now;\n    \n    // Transfer actual tokens\n    Ok(())\n}\n```"),
]
for name, q, a in VESTING:
    records.append(make_rec(f"### Question\n{q}\n\n### Answer\n{a}", "defi_vesting"))

# ── 5. Governance (10) ──
GOV = [
    ("proposal", "How do I implement proposal creation for a DAO?",
     "```rust\n#[account]\n#[derive(InitSpace)]\npub struct Proposal {\n    pub creator: Pubkey,\n    #[max_len(200)]\n    pub description: String,\n    pub votes_for: u64,\n    pub votes_against: u64,\n    pub start_time: i64,\n    pub end_time: i64,\n    pub executed: bool,\n    pub proposal_type: ProposalType,\n    pub bump: u8,\n}\n\n#[derive(AnchorSerialize, AnchorDeserialize, Clone, InitSpace)]\npub enum ProposalType {\n    ParameterChange { key: u8, value: u64 },\n    TreasurySpend { recipient: Pubkey, amount: u64 },\n    ProgramUpgrade { buffer: Pubkey },\n}\n```"),
    ("voting", "How do I implement token-weighted voting?",
     "```rust\n#[account]\n#[derive(InitSpace)]\npub struct VoteRecord {\n    pub voter: Pubkey,\n    pub proposal: Pubkey,\n    pub weight: u64,\n    pub support: bool,\n}\n\npub fn vote(ctx: Context<Vote>, support: bool) -> Result<()> {\n    let proposal = &mut ctx.accounts.proposal;\n    let clock = Clock::get()?;\n    require!(clock.unix_timestamp <= proposal.end_time, GovError::VotingEnded);\n    \n    // Weight = user's token balance (snapshot at proposal creation)\n    let weight = ctx.accounts.voter_token_account.amount;\n    require!(weight > 0, GovError::NoVotingPower);\n    \n    if support {\n        proposal.votes_for = proposal.votes_for.checked_add(weight).unwrap();\n    } else {\n        proposal.votes_against = proposal.votes_against.checked_add(weight).unwrap();\n    }\n    \n    // Record vote to prevent double-voting\n    let record = &mut ctx.accounts.vote_record;\n    record.voter = ctx.accounts.voter.key();\n    record.proposal = proposal.key();\n    record.weight = weight;\n    record.support = support;\n    Ok(())\n}\n```"),
    ("execute_proposal", "How do I execute a passed governance proposal?",
     "```rust\npub fn execute(ctx: Context<Execute>) -> Result<()> {\n    let proposal = &mut ctx.accounts.proposal;\n    let config = &ctx.accounts.config;\n    let clock = Clock::get()?;\n    \n    require!(clock.unix_timestamp > proposal.end_time, GovError::VotingNotEnded);\n    require!(!proposal.executed, GovError::AlreadyExecuted);\n    \n    let total_votes = proposal.votes_for + proposal.votes_against;\n    require!(total_votes >= config.quorum, GovError::QuorumNotReached);\n    require!(proposal.votes_for > proposal.votes_against, GovError::ProposalRejected);\n    \n    // Optional: timelock check\n    require!(\n        clock.unix_timestamp >= proposal.end_time + config.timelock_seconds,\n        GovError::TimelockActive\n    );\n    \n    proposal.executed = true;\n    \n    match proposal.proposal_type {\n        ProposalType::TreasurySpend { recipient, amount } => {\n            // CPI: transfer from treasury PDA\n        }\n        ProposalType::ParameterChange { key, value } => {\n            // Update config parameter\n        }\n        _ => {}\n    }\n    Ok(())\n}\n```"),
]
for name, q, a in GOV:
    records.append(make_rec(f"### Question\n{q}\n\n### Answer\n{a}", "defi_governance"))

# ── 6. Oracle integration (8) ──
ORACLES = [
    ("pyth", "How do I use Pyth price feeds in Anchor?",
     "```rust\nuse pyth_solana_receiver_sdk::price_update::PriceUpdateV2;\n\n#[derive(Accounts)]\npub struct UsePrice<'info> {\n    pub price_update: Account<'info, PriceUpdateV2>,\n}\n\npub fn get_sol_price(ctx: Context<UsePrice>) -> Result<u64> {\n    let price_update = &ctx.accounts.price_update;\n    let clock = Clock::get()?;\n    \n    // SOL/USD feed ID\n    let feed_id = get_feed_id_from_hex(\"0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d\")?;\n    \n    let price = price_update.get_price_no_older_than(\n        &clock,\n        60,  // Max 60 seconds old\n        &feed_id,\n    )?;\n    \n    msg!(\"SOL price: {} ± {} (expo: {})\", price.price, price.conf, price.exponent);\n    Ok(price.price as u64)\n}\n```"),
    ("switchboard", "How do I use Switchboard oracles?",
     "```rust\nuse switchboard_solana::AggregatorAccountData;\n\npub fn read_price(ctx: Context<ReadPrice>) -> Result<()> {\n    let feed = &ctx.accounts.switchboard_feed;\n    let data = AggregatorAccountData::new(feed)?;\n    \n    let value = data.get_result()?;\n    let price = value.try_into_f64()?;\n    \n    // Check staleness\n    let staleness = Clock::get()?.unix_timestamp - data.latest_confirmed_round.round_open_timestamp;\n    require!(staleness < 60, OracleError::StaleFeed);\n    \n    msg!(\"Price: {}\", price);\n    Ok(())\n}\n```"),
    ("twap", "How do I calculate a TWAP (Time-Weighted Average Price)?",
     "```rust\n#[account]\npub struct TwapState {\n    pub cumulative_price: u128,\n    pub last_price: u64,\n    pub last_timestamp: i64,\n    pub observations: u32,\n}\n\npub fn update_twap(state: &mut TwapState, new_price: u64) -> Result<()> {\n    let clock = Clock::get()?;\n    let elapsed = (clock.unix_timestamp - state.last_timestamp) as u128;\n    \n    state.cumulative_price += state.last_price as u128 * elapsed;\n    state.last_price = new_price;\n    state.last_timestamp = clock.unix_timestamp;\n    state.observations += 1;\n    Ok(())\n}\n\npub fn get_twap(state: &TwapState, period_seconds: i64) -> u64 {\n    let clock = Clock::get().unwrap();\n    let elapsed = (clock.unix_timestamp - state.last_timestamp) as u128;\n    let current_cumulative = state.cumulative_price + state.last_price as u128 * elapsed;\n    (current_cumulative / period_seconds as u128) as u64\n}\n```"),
    ("price_confidence", "How do I handle oracle price confidence intervals?",
     "```rust\n// Pyth provides confidence intervals with every price\nlet price = price_update.get_price_no_older_than(&clock, 60, &feed_id)?;\n\n// Reject if confidence is too wide (> 1% of price)\nlet confidence_ratio = price.conf as u128 * 10_000 / price.price.unsigned_abs() as u128;\nrequire!(confidence_ratio < 100, OracleError::PriceUncertain); // 1% max\n\n// For liquidations, use conservative price:\n// Collateral: price - confidence (lower bound)\n// Debt: price + confidence (upper bound)\nlet collateral_price = price.price - price.conf as i64;\nlet debt_price = price.price + price.conf as i64;\n```"),
]
for name, q, a in ORACLES:
    records.append(make_rec(f"### Question\n{q}\n\n### Answer\n{a}", "defi_oracles"))

# ── 7. NFT Marketplace (8) ──
NFT = [
    ("list_nft", "How do I implement NFT listing in a marketplace?",
     "```rust\n#[account]\n#[derive(InitSpace)]\npub struct Listing {\n    pub seller: Pubkey,\n    pub mint: Pubkey,\n    pub price: u64,\n    pub escrow: Pubkey,  // Token account holding the NFT\n    pub created_at: i64,\n    pub bump: u8,\n}\n\npub fn list(ctx: Context<ListNft>, price: u64) -> Result<()> {\n    require!(price > 0, MarketError::InvalidPrice);\n    \n    let listing = &mut ctx.accounts.listing;\n    listing.seller = ctx.accounts.seller.key();\n    listing.mint = ctx.accounts.mint.key();\n    listing.price = price;\n    listing.created_at = Clock::get()?.unix_timestamp;\n    listing.bump = ctx.bumps.listing;\n    \n    // Transfer NFT from seller to escrow PDA\n    token::transfer(\n        CpiContext::new(ctx.accounts.token_program.to_account_info(),\n            Transfer {\n                from: ctx.accounts.seller_token.to_account_info(),\n                to: ctx.accounts.escrow.to_account_info(),\n                authority: ctx.accounts.seller.to_account_info(),\n            }),\n        1,  // NFT amount is always 1\n    )?;\n    Ok(())\n}\n```"),
    ("buy_nft", "How do I implement NFT buying with royalties?",
     "```rust\npub fn buy(ctx: Context<BuyNft>) -> Result<()> {\n    let listing = &ctx.accounts.listing;\n    let price = listing.price;\n    \n    // Calculate fees\n    let marketplace_fee = price * 250 / 10_000;  // 2.5%\n    let royalty_fee = price * 500 / 10_000;        // 5% creator royalty\n    let seller_amount = price - marketplace_fee - royalty_fee;\n    \n    // Pay seller\n    system_program::transfer(CpiContext::new(/* ... */), seller_amount)?;\n    // Pay marketplace\n    system_program::transfer(CpiContext::new(/* ... */), marketplace_fee)?;\n    // Pay creator royalty\n    system_program::transfer(CpiContext::new(/* ... */), royalty_fee)?;\n    \n    // Transfer NFT from escrow to buyer\n    let seeds = &[b\"escrow\", listing.mint.as_ref(), &[listing.bump]];\n    token::transfer(\n        CpiContext::new_with_signer(/* ... */, &[seeds]),\n        1,\n    )?;\n    Ok(())\n}\n```"),
    ("auction", "How do I implement an English auction for NFTs?",
     "```rust\n#[account]\n#[derive(InitSpace)]\npub struct Auction {\n    pub seller: Pubkey,\n    pub mint: Pubkey,\n    pub highest_bid: u64,\n    pub highest_bidder: Pubkey,\n    pub end_time: i64,\n    pub min_bid_increment: u64,\n    pub settled: bool,\n    pub bump: u8,\n}\n\npub fn place_bid(ctx: Context<PlaceBid>, bid_amount: u64) -> Result<()> {\n    let auction = &mut ctx.accounts.auction;\n    let clock = Clock::get()?;\n    require!(clock.unix_timestamp < auction.end_time, AuctionError::Ended);\n    require!(\n        bid_amount >= auction.highest_bid + auction.min_bid_increment,\n        AuctionError::BidTooLow\n    );\n    \n    // Refund previous highest bidder\n    if auction.highest_bid > 0 {\n        // Transfer SOL back to previous bidder\n    }\n    \n    // Accept new bid\n    auction.highest_bid = bid_amount;\n    auction.highest_bidder = ctx.accounts.bidder.key();\n    \n    // Extend auction if bid in last 5 minutes\n    if auction.end_time - clock.unix_timestamp < 300 {\n        auction.end_time += 300;  // Anti-sniping\n    }\n    Ok(())\n}\n```"),
]
for name, q, a in NFT:
    records.append(make_rec(f"### Question\n{q}\n\n### Answer\n{a}", "defi_nft_marketplace"))

# ── 8. Escrow (5) ──
ESCROW = [
    ("basic_escrow", "How do I implement a basic escrow in Anchor?",
     "```rust\n#[account]\n#[derive(InitSpace)]\npub struct Escrow {\n    pub maker: Pubkey,\n    pub taker: Pubkey,\n    pub mint_a: Pubkey,\n    pub mint_b: Pubkey,\n    pub amount_a: u64,\n    pub expected_b: u64,\n    pub bump: u8,\n}\n\npub fn create_escrow(ctx: Context<CreateEscrow>, amount_a: u64, expected_b: u64) -> Result<()> {\n    let escrow = &mut ctx.accounts.escrow;\n    escrow.maker = ctx.accounts.maker.key();\n    escrow.mint_a = ctx.accounts.mint_a.key();\n    escrow.mint_b = ctx.accounts.mint_b.key();\n    escrow.amount_a = amount_a;\n    escrow.expected_b = expected_b;\n    escrow.bump = ctx.bumps.escrow;\n    \n    // Transfer token A from maker to escrow vault\n    token::transfer(CpiContext::new(/* ... */), amount_a)?;\n    Ok(())\n}\n\npub fn take_escrow(ctx: Context<TakeEscrow>) -> Result<()> {\n    let escrow = &ctx.accounts.escrow;\n    \n    // Taker sends token B to maker\n    token::transfer(CpiContext::new(/* ... */), escrow.expected_b)?;\n    \n    // Escrow PDA sends token A to taker\n    let seeds = &[b\"escrow\", escrow.maker.as_ref(), &[escrow.bump]];\n    token::transfer(\n        CpiContext::new_with_signer(/* ... */, &[seeds]),\n        escrow.amount_a,\n    )?;\n    \n    // Close escrow account\n    Ok(())\n}\n```"),
]
for name, q, a in ESCROW:
    records.append(make_rec(f"### Question\n{q}\n\n### Answer\n{a}", "defi_escrow"))

# ── Write output ──
PROCESSED.mkdir(parents=True, exist_ok=True)
out = PROCESSED / "synthetic-bulk11.jsonl"
with open(out, "w") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"Wrote {len(records)} records to {out}")
cats = {}
for r in records:
    c = r["metadata"]["category"]
    cats[c] = cats.get(c, 0) + 1
for c, n in sorted(cats.items()):
    print(f"  {c}: {n}")
